### ISSUE TITLE
macOS High Sierra: Echo example doesn't work

### ISSUE THREAD

**Issue by Y2JChamp** [sandeepmistry/bleno#358] opened 2017-12-19 14:02 UTC
Hi,
i've followed the instructions to install and launch bleno, but when i start main.js of echo example it stucks at the following output "bleno - echo".
I'm running it on a MacBook Air with Sierra (ver. 10.13.1)

Any help is appreciated
Thanks

**Comment by Arvinwolf91** [comment] 2018-01-09 08:24
Same problem using MacBook Air with Sierra 10.13.2. Were you able to fix it ?

**Comment by sandeepmistry** [comment] 2018-01-22 02:09
@Y2JChamp @Arvinwolf91 please provide feedback on PR #360.

**Comment by sandeepmistry** [comment] 2018-01-22 02:11
Closing this as a duplicate of https://github.com/sandeepmistry/bleno/issues/341.

**Closed by sandeepmistry** 2018-01-22 02:11 UTC
