### ISSUE TITLE
using bleno in a systemd service

### ISSUE THREAD

**Issue by arget888** [sandeepmistry/bleno#351] opened 2017-11-17 18:05 UTC
Hello,
I am using bleno in an systemd service. The service is waiting for the hci service and the blutooth service at my raspberry zero w with raspian installed. I am initialising all event listeners after the bluetooth service is up and running and after checking that the bluetooth device is realy up and assigned in hicitool. My problem is that bleno do not recognize that all neccesary services are up and running it says always that the state is poweredOff and if i reload the bleno module it says that the state of my adapter is unknown. how can i solve this?

**Comment by sandeepmistry** [comment] 2018-01-29 03:23
Closing as duplicate of https://github.com/sandeepmistry/bleno/issues/342.

**Closed by sandeepmistry** 2018-01-29 03:23 UTC
Labels: duplicate
