### ISSUE TITLE
After installing bleno, A2DP not work!

### ISSUE THREAD

**Issue by AlessandroFerri** [sandeepmistry/bleno#91] opened 2015-01-24 16:52 UTC
Hi Sandeep Mistry,

I have installed bleno on my raspberry and it works great, but now I can not connect with my iPhone or iPad for listening music via A2DP bluetooth. I can use bleno and BLE on the same USB dongle or is incompatible?
Can you help me?

**Comment by sandeepmistry** [comment] 2015-01-24 21:56
Duplicate of #90.

**Closed by sandeepmistry** 2015-01-24 21:56 UTC
Labels: duplicate
